package com.gonzalez.erp.modules.roles.entity;

public enum Permission {
    CREAR_PEDIDOS,
    ADMINISTRAR_CLIENTES,
    ADMINISTRAR_PRODUCTOS,
    ADMINISTRAR_CATEGORIAS,
    ADMINISTRAR_PRECIOS,
    AJUSTAR_STOCK,
    TRANSFERIR_STOCK,
    ADMINISTRAR_USUARIOS,
    VER_REPORTES,
    CREAR_ENVIOS,
    ACCEDER_TODAS_SUCURSALES,
    VER_PEDIDOS,
    PREPARAR_PEDIDOS,
    CONSULTAR_STOCK,
    CONSULTAR_ENVIOS
}
